/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWorkoutsRouteImport } from './routes/_app/workouts'
import { Route as AppTrendsRouteImport } from './routes/_app/trends'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPatientSummaryRouteImport } from './routes/_app/patient-summary'
import { Route as AppMedicationsRouteImport } from './routes/_app/medications'
import { Route as AppLabResultsRouteImport } from './routes/_app/lab-results'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppConditionsRouteImport } from './routes/_app/conditions'
import { Route as AppAllergiesRouteImport } from './routes/_app/allergies'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsRoute = AppWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientSummaryRoute = AppPatientSummaryRouteImport.update({
  id: '/patient-summary',
  path: '/patient-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppMedicationsRoute = AppMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => AppRoute,
} as any)
const AppLabResultsRoute = AppLabResultsRouteImport.update({
  id: '/lab-results',
  path: '/lab-results',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppConditionsRoute = AppConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => AppRoute,
} as any)
const AppAllergiesRoute = AppAllergiesRouteImport.update({
  id: '/allergies',
  path: '/allergies',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/allergies': typeof AppAllergiesRoute
  '/conditions': typeof AppConditionsRoute
  '/import': typeof AppImportRoute
  '/insights': typeof AppInsightsRoute
  '/lab-results': typeof AppLabResultsRoute
  '/medications': typeof AppMedicationsRoute
  '/patient-summary': typeof AppPatientSummaryRoute
  '/settings': typeof AppSettingsRoute
  '/trends': typeof AppTrendsRoute
  '/workouts': typeof AppWorkoutsRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/allergies': typeof AppAllergiesRoute
  '/conditions': typeof AppConditionsRoute
  '/import': typeof AppImportRoute
  '/insights': typeof AppInsightsRoute
  '/lab-results': typeof AppLabResultsRoute
  '/medications': typeof AppMedicationsRoute
  '/patient-summary': typeof AppPatientSummaryRoute
  '/settings': typeof AppSettingsRoute
  '/trends': typeof AppTrendsRoute
  '/workouts': typeof AppWorkoutsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/sign-up': typeof SignUpRoute
  '/_app/allergies': typeof AppAllergiesRoute
  '/_app/conditions': typeof AppConditionsRoute
  '/_app/import': typeof AppImportRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/lab-results': typeof AppLabResultsRoute
  '/_app/medications': typeof AppMedicationsRoute
  '/_app/patient-summary': typeof AppPatientSummaryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trends': typeof AppTrendsRoute
  '/_app/workouts': typeof AppWorkoutsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/allergies'
    | '/conditions'
    | '/import'
    | '/insights'
    | '/lab-results'
    | '/medications'
    | '/patient-summary'
    | '/settings'
    | '/trends'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/allergies'
    | '/conditions'
    | '/import'
    | '/insights'
    | '/lab-results'
    | '/medications'
    | '/patient-summary'
    | '/settings'
    | '/trends'
    | '/workouts'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/_app/allergies'
    | '/_app/conditions'
    | '/_app/import'
    | '/_app/insights'
    | '/_app/lab-results'
    | '/_app/medications'
    | '/_app/patient-summary'
    | '/_app/settings'
    | '/_app/trends'
    | '/_app/workouts'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts': {
      id: '/_app/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trends': {
      id: '/_app/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patient-summary': {
      id: '/_app/patient-summary'
      path: '/patient-summary'
      fullPath: '/patient-summary'
      preLoaderRoute: typeof AppPatientSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/medications': {
      id: '/_app/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof AppMedicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lab-results': {
      id: '/_app/lab-results'
      path: '/lab-results'
      fullPath: '/lab-results'
      preLoaderRoute: typeof AppLabResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conditions': {
      id: '/_app/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof AppConditionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/allergies': {
      id: '/_app/allergies'
      path: '/allergies'
      fullPath: '/allergies'
      preLoaderRoute: typeof AppAllergiesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAllergiesRoute: typeof AppAllergiesRoute
  AppConditionsRoute: typeof AppConditionsRoute
  AppImportRoute: typeof AppImportRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLabResultsRoute: typeof AppLabResultsRoute
  AppMedicationsRoute: typeof AppMedicationsRoute
  AppPatientSummaryRoute: typeof AppPatientSummaryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppWorkoutsRoute: typeof AppWorkoutsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAllergiesRoute: AppAllergiesRoute,
  AppConditionsRoute: AppConditionsRoute,
  AppImportRoute: AppImportRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLabResultsRoute: AppLabResultsRoute,
  AppMedicationsRoute: AppMedicationsRoute,
  AppPatientSummaryRoute: AppPatientSummaryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppWorkoutsRoute: AppWorkoutsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
